const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{ТайловыйФон: 0},
	{геор: 0},
	{Текст: 0},
	{кнопка: 0},
	{Текст2: 0},
	{Текст3: 0},
	{ТайловыйФон2: 0},
	{ТайловыйФон3: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{Спрайт: 0},
	{Твёрдый: 0},
	{платформа: 0},
	{Спрайт2: 0},
	{Синусоида: 0},
	{привединие: 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{Пуля: 0},
	{граната: 0},
	{Мышь: 0},
	{ТайловыйФон4: 0},
	{ТайловыйФон5: 0},
	{ТайловыйФон6: 0},
	{ТайловыйФон7: 0},
	{ТайловыйФон8: 0},
	{ТайловыйФон9: 0},
	{ТайловыйФон10: 0},
	{Текст4: 0},
	{Текст5: 0},
	{Кнопка2: 0},
	{ТайловыйФон11: 0},
	{Текст6: 0},
	{ТайловыйФон12: 0},
	{Текст7: 0},
	{ВМеню: 0},
	{Спрайт3: 0},
	{Текст8: 0},
	{Спрайт8: 0},
	{Текст9: 0},
	{ТайловыйФон13: 0},
	{ТайловыйФон14: 0},
	{ТайловыйФон15: 0},
	{ТайловыйФон16: 0},
	{ТайловыйФон17: 0},
	{Спрайт9: 0},
	{Текст10: 0},
	{Спрайт10: 0},
	{Спрайт11: 0},
	{Спрайт12: 0},
	{Спрайт13: 0},
	{Спрайт14: 0}
];

self.InstanceType = {
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	геор: class extends self.ITextInstance {},
	Текст: class extends self.ITextInstance {},
	кнопка: class extends self.IButtonInstance {},
	Текст2: class extends self.ITextInstance {},
	Текст3: class extends self.ITextInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	платформа: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	привединие: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	граната: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	ТайловыйФон4: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон5: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон6: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон7: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон8: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон9: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон10: class extends self.ITiledBackgroundInstance {},
	Текст4: class extends self.ITextInstance {},
	Текст5: class extends self.ITextInstance {},
	Кнопка2: class extends self.IButtonInstance {},
	ТайловыйФон11: class extends self.ITiledBackgroundInstance {},
	Текст6: class extends self.ITextInstance {},
	ТайловыйФон12: class extends self.ITiledBackgroundInstance {},
	Текст7: class extends self.ITextInstance {},
	ВМеню: class extends self.IButtonInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Текст8: class extends self.ITextInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Текст9: class extends self.ITextInstance {},
	ТайловыйФон13: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон14: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон15: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон16: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон17: class extends self.ITiledBackgroundInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Текст10: class extends self.ITextInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	Спрайт14: class extends self.ISpriteInstance {}
}